[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
course7 = "CNaGveTjTsJ4iWLLMe9gghPoYtEDMsUsJPRosqhQs6RY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
